### ISSUE TITLE
Apparent bug with implicit/explicit arguments in 'class Category'

### ISSUE THREAD

**Issue by kim-em** [semorrison/proof#2]

**Comment by kim-em** [comment]
We should make a minimal example, and post to lean-user (or just the lean github issues list, if it's clearly a bug).

**Comment by Xitian9** [comment]
I think this should be filed under ‘feature’ rather than ‘bug’. In our cases it's slightly unintuitive, but would be the desired outcome in other examples. If it causes a problem, the best solution is probably to define helper functions.

**Comment by kim-em** [comment]
Hi Stephen, I read your comment, but don't understand what's going on.

**Comment by kim-em** [comment]
Okay, got it, more or less. I'll add a link to this commit.

**Comment by Xitian9** [comment]
Perhaps a clearer way to say this: the typeclass `foo.baz : {A : Type} [c : @foo A], A → A` is equivalent to
`foo.baz : Π {A : Type} [c : @foo A], Π (x : A), A`, which is equivalent to `foo.baz : Π {A : Type} [c : @foo A] (x : A), A`. Expressed this way, it is clear why the `{A : Type}` can be implicit, which would not be true if end type were just `A` rather than `A → A`.
